### ISSUE TITLE
how to convert to plugin installed in go-ipfs

### ISSUE THREAD

**Issue by mtiger2k** [ceramicnetwork/go-dag-jose#1]
Hi expert,

this is a good repo, and I want to use it as plugin to installed in go-ipfs.
can you direct me how to convert it to go plugin?

thanks

**Comment by alexjg** [comment]
Apologies for late response. I'm not entirely sure what you are trying to achieve here, are you trying to use go-ipld-prime with the existing go-ipfs codebase?

**Comment by ukstv** [comment]
Is it stale? Can we close it? @oed

**Comment by oed** [comment]
yes, this plugin will soon be merged upstream.
