### ISSUE TITLE
Create test for ipfs-http-client

### ISSUE THREAD

**Issue by smrz2001** [ceramicnetwork/go-dag-jose#10]
That tests creating and retrieving dag-jose objects from ipfs using the ipfs-http-client. Tests should be configurable to point either to a js-ipfs or go-ipfs daemon.

[Original issue](https://github.com/3box/ceramic/issues/246)

Make a simple js script that tests the functionality.

**Comment by oed** [comment]
Closing in favor of https://github.com/ceramicnetwork/ceramic/issues/207

cc @glcohen
