### ISSUE TITLE
Validate / update the go-dag-jose plugin

### ISSUE THREAD

**Issue by smrz2001** [ceramicnetwork/go-dag-jose#8]
We need to confirm the following properties:

We should run the tests with the latest 0.9.0 go-ipfs release. We need to manually compile the go plugin.

## Basic testing with go-ipfs

We need to make sure that go-ipfs with a go-dag-jose plugin works the same as js-ipfs from the perspective of the ipfs-http-client. We should also make sure that some basic commands in go-ipfs works as expected.

We should have a basic script that creates a dag-jose object, puts it into the dag (ipfs.dag.put), retrieves it from the dag (ipfs.dag.get), and confirms that the retrived object is correctly formatted, and the same JWS object get's the same CID in both cases.

Run the tests:

   * on js-ipfs daemon
  *  on go-ipfs daemon

## go-ipfs cli

We want to be able to retrieve a dag-jose object from the ipfs cli and have it outputted in the console. When 
`ipfs dag get <dag-jose-cid>` is exectued we should see the dag-jose object outputted in json format.

Note that this is not a strict requirement for js-ceramic to work properly.

**Comment by smrz2001** [comment]
[Original ticket](https://github.com/3box/ceramic/issues/245)

**Comment by oed** [comment]
duplicate closing

**Comment by oed** [comment]
@smrz2001
